Docs
kubescape/config-service pull request #30
Opened 2022-12-20 13:32 UTC by avrahams

2022-12-20 18:47 UTC, dwertent requested changes
While reviewing this PR I took a broader look at the repo and I have some comments to make:

### General
* Please add the `.vscode` to `.gitignore`
* Why are we importing the jenkinstools? The image should be built using the GitHub workflows 
* Please add a file for maintainers and license 
* Why is this project public? We should probably make it public only when we plan on moving the BE source code to the public

### Docs related
* I'm missing here: how to build, test, and run this project locally
* Swagger?

### Code related
* I believe the [handlers](https://github.com/kubescape/config-service/tree/master/handlers) should be wrapped in a version (the directory structure should look `config-service/handlers/v1/`

**I must say the overall execution of this project is amazing :)**

2022-12-20 18:47 UTC, dwertent commented on README.md
> +### Todo List
```suggestion

```

2022-12-21 11:13 UTC, avrahams commented
> * Why are we importing the jenkinstools? The image should be built using the GitHub workflows
We plan to move it to GitHub actions when the infra is ready
> * Why is this project public? We should probably make it public only when we plan on moving the BE source code to the public
Thi
> 
> ### Docs related
> * I'm missing here: how to build, test, and run this project locally
> * Swagger?
> 
> ### Code related
> * I believe the [handlers](https://github.com/kubescape/config-service/tree/master/handlers) should be wrapped in a version (the directory structure should look `config-service/handlers/v1/`
> 
> **I must say the overall execution of this project is amazing :)**

2022-12-22 12:48 UTC, dwertent approved these changes

2022-12-22 12:48 UTC, merged