Push Notification in Config service + customer post
kubescape/config-service pull request #47
Opened 2023-01-18 17:46 UTC by avrahams

- Add generic add to map handing 
- Fix and test PUT /customer
- Add API for adding and removing push notification from notification config 
```go
PUT /v1_notification_config/latestPushReport/:clusterName
Body: 
type PushReport struct {
	Cluster         string    `json:"custer,omitempty" bson:"custer,omitempty"`
	ReportGUID      string    `json:"reportGUID,omitempty" bson:"reportGUID,omitempty"`
	ScanType        ScanType  `json:"scanType" bson:"scanType"`
	Timestamp       time.Time `json:"timestamp,omitempty" bson:"timestamp,omitempty"`
	FailedResources uint64    `json:"failedResources,omitempty" bson:"failedResources,omitempty"`
}
```
And
```go
DELETE  /v1_notification_config/latestPushReport/:clusterName
```

2023-01-18 18:06 UTC, Bezbran requested changes

2023-01-18 18:06 UTC, Bezbran commented on handlers/plugins.go
> +type EmbeddedDataMiddleware func(c *gin.Context) (pathToArray string, valueToAdd interface{}, queryFilter *db.FilterBuilder, valid bool)
I think that this is too tighten to MongoBD implementation. Why is the caller of the handler should be aware if this is an embedded document or not

2023-01-18 18:06 UTC, Bezbran commented on handlers/routes.go
> +	arraysHandlers            []embeddedDataRouteOptions //default nil, list of array handlers to put and delete items from document internal array
The same. embedded or not is subject to the DB layer, not for routing layer

2023-01-18 18:38 UTC, avrahams commented on handlers/routes.go
> +	arraysHandlers            []embeddedDataRouteOptions //default nil, list of array handlers to put and delete items from document internal array
Routing layer serves a document 
if it also want to serve operations on partial data of the doc it should be aware since it is the one the exposes this api

2023-01-19 11:20 UTC, avrahams commented on handlers/plugins.go
> +type EmbeddedDataMiddleware func(c *gin.Context) (pathToArray string, valueToAdd interface{}, queryFilter *db.FilterBuilder, valid bool)
@Bezbran I did some refectory 
I changed the plugin name EmbeddedDataMiddleware   => ContainerHandler
The ContainerHandler only returns the value of the item to add and the name of the container (no filter builder)

Also besides the container type the route level need to define the desired behavior of the container 
like ```array-with-unique-values``` or ```fixed-size-stack``` etc...

But eventually since we do not have a schema the only one that knows if the container is an array or map is  the end-route the knows the data 

the desired operation of the container

2023-01-23 10:08 UTC, Bezbran approved these changes

2023-01-23 11:30 UTC, merged