Unique values
kubescape/config-service pull request #82
Opened 2023-07-26 11:05 UTC by avrahams

When V2ListRequest route option is set than add also 
POST uniqueValues 
with armotypes.UniqueValuesRequestV2 in body 
% UniqueValuesResponseV2 response 

Add uniqueValues tester

2023-07-26 12:16 UTC, Bezbran requested changes

2023-07-26 12:16 UTC, Bezbran commented on db/utils.go
> +		filedRef := "$" + field
in goroutine

2023-07-26 12:50 UTC, Bezbran requested changes

2023-07-26 13:03 UTC, RinaO1234 commented on db/utils.go
> +	aggregatedResults := &armotypes.UniqueValuesResponseV2{
split to method

2023-07-26 13:06 UTC, RinaO1234 commented on db/utils.go
> +			aggregateResultErr = errors.New("failed to cast key")
add more details to errors

2023-07-26 13:08 UTC, RinaO1234 commented on db/utils.go
> +	defer log.LogNTraceEnterExit(fmt.Sprintf("AdminAggregate %+v", findOps), c)()
why do we use defer ? and consider adding more debug logs before goroutines

2023-07-26 14:20 UTC, RinaO1234 approved these changes

2023-07-26 14:22 UTC, RinaO1234 commented on db/utils.go
> +	defer log.LogNTraceEnterExit(fmt.Sprintf("AdminAggregate %+v", findOps), c)()
cosider additional debug messages before / in gouruoutines, why do we use defer?

2023-07-26 14:35 UTC, Bezbran approved these changes

2023-07-26 14:35 UTC, avrahams commented on db/utils.go
> +		filedRef := "$" + field
done

2023-07-26 14:36 UTC, merged

2023-07-30 07:10 UTC, avrahams commented on db/utils.go
> +	defer log.LogNTraceEnterExit(fmt.Sprintf("AdminAggregate %+v", findOps), c)()
The defer is on the retuned function - so it prints a message (and add event to telementry) on enter the function and when existing it - for instance
```json
{"level":"info","ts":"2023-07-30T10:09:26.480561323+03:00","msg":"UpdateDocument","method":"PUT","query":"","path":"/v1_vulnerability_exception_policy","trace_id":"32e1c13ad87d8a273fd41c077f2fad25","span_id":"2ce5815fb7a55e20"}
{"level":"info","ts":"2023-07-30T10:09:26.481572213+03:00","msg":"UpdateDocument completed","method":"PUT","query":"","path":"/v1_vulnerability_exception_policy","trace_id":"32e1c13ad87d8a273fd41c077f2fad25","span_id":"2ce5815f
```