support date field type using schema info
kubescape/config-service pull request #97
Opened 2023-11-20 17:46 UTC by refaelm92

Signed-off-by: refaelm <refaelm@armosec.io>

2023-11-20 18:05 UTC, avrahams requested changes

2023-11-20 18:05 UTC, avrahams commented on utils/utils.go
> +		case types.Date:
it will be nicer to add a function to schema info - something like IsDate() bool

2023-11-20 18:05 UTC, avrahams commented on handlers/v2ListRequest.go
> +func v2List2FindOptions(request armotypes.V2ListRequest, schemaInfo types.SchemaInfo) (*db.FindOptions, error) {
I think it will be much nicer to pass the context and pull the schema just when you need it 

We store a lot of stuff on the context - so if we will need something else we will not need to another param and drill it down again

2023-11-20 19:08 UTC, avrahams commented on types/api_info.go
> +	FieldsType map[string]FieldType `json:"fieldsType,omitempty"`
let's add a function something like IsDate(field string) bool

2023-11-21 07:01 UTC, refaelm92 commented on service_test.go
> +	commonTest(suite, consts.VulnerabilityExceptionPolicyPath, vulnerabilities, modifyFunc, commonCmpFilter, ignoreTime)
added expiration date to the vuln json

2023-11-21 08:46 UTC, avrahams requested changes

2023-11-21 08:46 UTC, avrahams commented on handlers/v2ListRequest.go
> +func v2List2FindOptions(ctx context.Context, request armotypes.V2ListRequest) (*db.FindOptions, error) {
As long as we inside the handlers package better to sent the context as c *gin.Context

2023-11-21 09:40 UTC, avrahams approved these changes

2023-11-21 10:07 UTC, merged